name = "PolygonArea"
uuid = "f818da22-b9d0-4424-a67f-6ca99e6cd93f"
authors = ["Matthieu Ancellin <matthieu.ancellin@ens-paris-saclay.fr>"]
version = "0.1.0"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
